### ISSUE TITLE
OAuth Clarification

### ISSUE THREAD

**Issue by tomlongo** [nationbuilder/nationbuilder-ios#39]
I have a quick question relating to oAuth. 

I would like the iOS app I've created to be general purpose, so that anyone can install it and authenticate using their own nation's slug right away. However, it seems that it doesn't work this way; the user must first install the corresponding NationBuilder app within their Nation's control panel in order to get the app's authentication to work. 

Is this the expected behaviour, or have I implemented something incorrectly on my end?

**Comment by hlfcoding** [comment]
Yes, that is the expected behavior. People of a nation can only use the app if it's been installed by someone with enough access.

**Comment by ryanaspire** [comment]
From my experience this is only the behaviour when using the iOS SDK. The previous version of our app used oAuth via the web. Users were not required to install the app via the control panel. As long as they had permissions to use the API, the oAuth worked.

Can you confirm this and explain the thinking behind why the iOS SDK works differently?

**Comment by hlfcoding** [comment]
When was the previous version of your app? Using NationBuilder apps started requiring installation (either during authorization by an admin, or through the control panel by someone with enough access) around fall of last year.

The iOS SDK is a transparent layer to the NB API and OAuth layers. It does not perform authentication or authorization in any special, non-standard way. It uses the implicit OAuth grant flow.
