### ISSUE TITLE
Access Token Expiring

### ISSUE THREAD

**Issue by tomlongo** [nationbuilder/nationbuilder-ios#40]
Hey guys, every once in a while I'm finding the access token expires, causing a 401 response from the API. I've double checked to make sure the access token is being sent with the request and it is, so I'm guessing it's just expired. 

Under what circumstances should the access token expire? I'm wondering it it's inactivity, or perhaps a user logging in to the same account on a different device?

**Comment by hlfcoding** [comment]
We have an expiration field on the app itself that defaults to 30 days. This field will be respected for any pre-authorizations of the token response type. Hope the info helps; see responses on this [post](http://nationbuilder.com/danielmroberts/does_access_token_expire_oauth_token_response_includes_expires_in_attribute) for more detail.

Also, I notice you've been updating your fork of this project. Being unable to file an issue there, I was wondering if future pull requests to merge your changes back upstream is in the cards? Resourcing constraints prevent me from maintaining this project as much as I'd like. If you're interested, we can continue this discussion elsewhere.
